# (PART\*) Appendix {-}

# Useful Internet Resources

## Homepages
[Quick-R](https://www.statmethods.net/) has been a go-to reference when you look up simple examples for quite some time. It is a really helpful source.

[This](https://github.com/erikgahner/PolData) is a nice overview over all kinds of PolSci and IR data sets that are out there.

Data Science is fun! Why not starting your own project on a topic that catches your interest? You could share your insights as a homepage. [Lillian Petersen](https://lillianpetersen.github.io/home/) could be a great inspiration.

The project [Seeing Theory](https://seeing-theory.brown.edu/index.html) is a visually really beautiful and interactive take on what we are doing in this class. Note: The authors are undergrads from Brown University.




## Online Books

Here is another good book that covers all we do in depth: Andrew Gelman, Jennifer Hill and Aki Vehtari (2020): "Regression and Other Stories". You can download it [here](https://avehtari.github.io/ROS-Examples/). (all legal...)

The [LOST](https://lost-stats.github.io/) homepage is a bit of a repository for all kinds of models. It not only has code in R, but also a couple of other relevant statistical softwares, such as Julia or Python.

If you want to dig a little deeper on the causal aspects, you can check out this beautiful online book titled [Causal Inference: The Mix Tape](https://mixtape.scunning.com/index.html). Also available as a print version of course...

If you want to go even further down the causal path, this is another module at Mannheim University that also comes with a [teaching homepage](https://bookdown.org/paul/applied-causal-analysis/).


Interested in Data Visualization? [This](http://cup.columbia.edu/book/better-data-visualizations/9780231193115) is a really great book on the topic from Jonathan Schwabish.

If you are keen to critically reflecting on what you are doing when you are analysing data, go and read [Critical Thinking](https://uk.sagepub.com/en-gb/eur/critical-thinking/book248140) from Tom Chatfield. He also has a [great video](https://www.youtube.com/watch?v=SY-CMrGp9Xs) where he explains the core ideas.



<!-- # Bibliography -->
<!-- \ref{@Bibliography} -->

