<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Multivariate Regression and Heterogenous Treatment Effects | PL 9248 Data Science for Politics and IR</title>
  <meta name="description" content="This is the website for the Data Science Class." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Multivariate Regression and Heterogenous Treatment Effects | PL 9248 Data Science for Politics and IR" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the website for the Data Science Class." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Multivariate Regression and Heterogenous Treatment Effects | PL 9248 Data Science for Politics and IR" />
  
  <meta name="twitter:description" content="This is the website for the Data Science Class." />
  

<meta name="author" content="Christian Arnold, Cardiff University" />


<meta name="date" content="2023-04-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="causal-statements-from-observational-data.html"/>
<link rel="next" href="useful-internet-resources.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<p class="verticalhorizontal" style="text-align:center;">
<img src="logo.jpg" height="80">
</p>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#data-to-answer-your-questions"><i class="fa fa-check"></i>Data to Answer Your Questions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#your-weekly-data-workout"><i class="fa fa-check"></i>Your Weekly Data Workout</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#work-through-this-homepage"><i class="fa fa-check"></i>1 Work Through This Homepage</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#apply-your-knowledge-in-our-workshops"><i class="fa fa-check"></i>2 Apply Your Knowledge in Our Workshops</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bring-your-questions-to-the-seminars"><i class="fa fa-check"></i>3 Bring Your Questions to the Seminars</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#read-guideance-on-planning-and-structuring"><i class="fa fa-check"></i>4 Read Guideance on Planning and Structuring</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-module-webpage"><i class="fa fa-check"></i>The Module Webpage</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#getting-in-touch"><i class="fa fa-check"></i>Getting in Touch</a></li>
</ul></li>
<li class="part"><span><b>Scenario I: The Data Report</b></span></li>
<li class="chapter" data-level="1" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html"><i class="fa fa-check"></i><b>1</b> Tools for Working with Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#what-is-in-a-data-spreadsheet"><i class="fa fa-check"></i><b>1.1</b> What Is In a Data Spreadsheet?</a></li>
<li class="chapter" data-level="1.2" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#key-concepts"><i class="fa fa-check"></i><b>1.2</b> Key Concepts</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#what-is-a-statistic"><i class="fa fa-check"></i><b>1.2.1</b> What is a Statistic?</a></li>
<li class="chapter" data-level="1.2.2" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#some-more-definitions"><i class="fa fa-check"></i><b>1.2.2</b> Some More Definitions</a></li>
<li class="chapter" data-level="1.2.3" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#types-of-data"><i class="fa fa-check"></i><b>1.2.3</b> Types of Data</a></li>
<li class="chapter" data-level="1.2.4" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#data-in-action"><i class="fa fa-check"></i><b>1.2.4</b> Data in Action</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#meet-r"><i class="fa fa-check"></i><b>1.3</b> Meet: R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#install-r"><i class="fa fa-check"></i><b>1.3.1</b> Install R</a></li>
<li class="chapter" data-level="1.3.2" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#install-r-studio"><i class="fa fa-check"></i><b>1.3.2</b> Install R Studio</a></li>
<li class="chapter" data-level="1.3.3" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#how-to-work-with-r"><i class="fa fa-check"></i><b>1.3.3</b> How to Work with R</a></li>
<li class="chapter" data-level="1.3.4" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#first-steps-in-r"><i class="fa fa-check"></i><b>1.3.4</b> First Steps in R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tools-for-working-with-data.html"><a href="tools-for-working-with-data.html#readings-for-this-week"><i class="fa fa-check"></i><b>1.4</b> Readings for This Week</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="describing-data.html"><a href="describing-data.html"><i class="fa fa-check"></i><b>2</b> Describing Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="describing-data.html"><a href="describing-data.html#statistics-to-summarise-data"><i class="fa fa-check"></i><b>2.1</b> Statistics to Summarise Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="describing-data.html"><a href="describing-data.html#tables"><i class="fa fa-check"></i><b>2.1.1</b> Tables</a></li>
<li class="chapter" data-level="2.1.2" data-path="describing-data.html"><a href="describing-data.html#central-tendencies"><i class="fa fa-check"></i><b>2.1.2</b> Central Tendencies</a></li>
<li class="chapter" data-level="2.1.3" data-path="describing-data.html"><a href="describing-data.html#spread"><i class="fa fa-check"></i><b>2.1.3</b> Spread</a></li>
<li class="chapter" data-level="2.1.4" data-path="describing-data.html"><a href="describing-data.html#ratios-and-rates"><i class="fa fa-check"></i><b>2.1.4</b> Ratios and Rates</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="describing-data.html"><a href="describing-data.html#data-management-with-r"><i class="fa fa-check"></i><b>2.2</b> Data Management with R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="describing-data.html"><a href="describing-data.html#libraries"><i class="fa fa-check"></i><b>2.2.1</b> Libraries</a></li>
<li class="chapter" data-level="2.2.2" data-path="describing-data.html"><a href="describing-data.html#setting-the-working-directory"><i class="fa fa-check"></i><b>2.2.2</b> Setting the Working Directory</a></li>
<li class="chapter" data-level="2.2.3" data-path="describing-data.html"><a href="describing-data.html#reading-data"><i class="fa fa-check"></i><b>2.2.3</b> Reading Data</a></li>
<li class="chapter" data-level="2.2.4" data-path="describing-data.html"><a href="describing-data.html#saving-data"><i class="fa fa-check"></i><b>2.2.4</b> Saving Data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="describing-data.html"><a href="describing-data.html#describing-data-using-r"><i class="fa fa-check"></i><b>2.3</b> Describing Data Using R</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="describing-data.html"><a href="describing-data.html#working-with-data-frames"><i class="fa fa-check"></i><b>2.3.1</b> Working with Data Frames</a></li>
<li class="chapter" data-level="2.3.2" data-path="describing-data.html"><a href="describing-data.html#central-tendencies-1"><i class="fa fa-check"></i><b>2.3.2</b> Central Tendencies</a></li>
<li class="chapter" data-level="2.3.3" data-path="describing-data.html"><a href="describing-data.html#spread-1"><i class="fa fa-check"></i><b>2.3.3</b> Spread</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="describing-data.html"><a href="describing-data.html#readings-for-this-week-1"><i class="fa fa-check"></i><b>2.4</b> Readings for This Week</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualising-data.html"><a href="visualising-data.html"><i class="fa fa-check"></i><b>3</b> Visualising Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visualising-data.html"><a href="visualising-data.html#communicating-with-data-effectively"><i class="fa fa-check"></i><b>3.1</b> Communicating with Data Effectively</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="visualising-data.html"><a href="visualising-data.html#thinking-about-your-data-visualisation"><i class="fa fa-check"></i><b>3.1.1</b> Thinking About your Data Visualisation</a></li>
<li class="chapter" data-level="3.1.2" data-path="visualising-data.html"><a href="visualising-data.html#visualising-the-data"><i class="fa fa-check"></i><b>3.1.2</b> Visualising ‘The Data’</a></li>
<li class="chapter" data-level="3.1.3" data-path="visualising-data.html"><a href="visualising-data.html#visualising-typical-values-and-spreads"><i class="fa fa-check"></i><b>3.1.3</b> Visualising Typical Values and Spreads</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="visualising-data.html"><a href="visualising-data.html#plotting-data-with-r"><i class="fa fa-check"></i><b>3.2</b> Plotting Data with R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="visualising-data.html"><a href="visualising-data.html#basics-in-plotting"><i class="fa fa-check"></i><b>3.2.1</b> Basics in Plotting</a></li>
<li class="chapter" data-level="3.2.2" data-path="visualising-data.html"><a href="visualising-data.html#colours"><i class="fa fa-check"></i><b>3.2.2</b> Colours</a></li>
<li class="chapter" data-level="3.2.3" data-path="visualising-data.html"><a href="visualising-data.html#visualising-nominal-and-ordinal-data"><i class="fa fa-check"></i><b>3.2.3</b> Visualising Nominal and Ordinal Data</a></li>
<li class="chapter" data-level="3.2.4" data-path="visualising-data.html"><a href="visualising-data.html#visualising-continuous-data"><i class="fa fa-check"></i><b>3.2.4</b> Visualising Continuous Data</a></li>
<li class="chapter" data-level="3.2.5" data-path="visualising-data.html"><a href="visualising-data.html#boxplots"><i class="fa fa-check"></i><b>3.2.5</b> Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="visualising-data.html"><a href="visualising-data.html#readings-for-this-week-2"><i class="fa fa-check"></i><b>3.3</b> Readings for This Week</a></li>
</ul></li>
<li class="part"><span><b>Scenario II: Knowing It All By Knowing A Few</b></span></li>
<li class="chapter" data-level="4" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html"><i class="fa fa-check"></i><b>4</b> Testing a Hypothesis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#generating-good-hypotheses"><i class="fa fa-check"></i><b>4.1</b> Generating Good Hypotheses</a></li>
<li class="chapter" data-level="4.2" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#studying-our-sample"><i class="fa fa-check"></i><b>4.2</b> Studying Our Sample</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#investigating-the-hypothesis"><i class="fa fa-check"></i><b>4.2.1</b> Investigating the Hypothesis</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#is-what-we-see-just-coincidence"><i class="fa fa-check"></i><b>4.3</b> Is What We See Just Coincidence?</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#are-two-cohorts-the-same"><i class="fa fa-check"></i><b>4.3.1</b> Are Two Cohorts the Same?</a></li>
<li class="chapter" data-level="4.3.2" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#how-can-we-tell-the-difference"><i class="fa fa-check"></i><b>4.3.2</b> How Can We Tell the Difference?</a></li>
<li class="chapter" data-level="4.3.3" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#hypothesis-testing"><i class="fa fa-check"></i><b>4.3.3</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="4.3.4" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#test-test-test"><i class="fa fa-check"></i><b>4.3.4</b> Test! Test! Test!</a></li>
<li class="chapter" data-level="4.3.5" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#type-1-and-type-2-errors"><i class="fa fa-check"></i><b>4.3.5</b> Type 1 and Type 2 Errors</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#coding"><i class="fa fa-check"></i><b>4.4</b> Coding</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#data-management"><i class="fa fa-check"></i><b>4.4.1</b> Data Management</a></li>
<li class="chapter" data-level="4.4.2" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#hypothesis-testing-1"><i class="fa fa-check"></i><b>4.4.2</b> Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="testing-a-hypothesis.html"><a href="testing-a-hypothesis.html#reading-for-this-week"><i class="fa fa-check"></i><b>4.5</b> Reading for This Week</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html"><i class="fa fa-check"></i><b>5</b> Why Does Hypothesis Testing Work? A Primer on Probability</a>
<ul>
<li class="chapter" data-level="5.1" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#distributions"><i class="fa fa-check"></i><b>5.1</b> Distributions</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#probability"><i class="fa fa-check"></i><b>5.1.1</b> Probability</a></li>
<li class="chapter" data-level="5.1.2" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#distribution"><i class="fa fa-check"></i><b>5.1.2</b> Distribution</a></li>
<li class="chapter" data-level="5.1.3" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#the-normal-distribution"><i class="fa fa-check"></i><b>5.1.3</b> The Normal Distribution</a></li>
<li class="chapter" data-level="5.1.4" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#your-standard-measure-z-scores"><i class="fa fa-check"></i><b>5.1.4</b> Your Standard Measure z-scores</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#inference"><i class="fa fa-check"></i><b>5.2</b> Inference</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#some-key-concepts"><i class="fa fa-check"></i><b>5.2.1</b> Some Key Concepts</a></li>
<li class="chapter" data-level="5.2.2" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#population-and-samples"><i class="fa fa-check"></i><b>5.2.2</b> Population and Samples</a></li>
<li class="chapter" data-level="5.2.3" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>5.2.3</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="5.2.4" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#summing-up-what-is-inference"><i class="fa fa-check"></i><b>5.2.4</b> Summing Up: What is Inference?</a></li>
<li class="chapter" data-level="5.2.5" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#confidence-intervals-being-95-certain"><i class="fa fa-check"></i><b>5.2.5</b> Confidence Intervals: Being 95% Certain</a></li>
<li class="chapter" data-level="5.2.6" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#revisiting-t-tests"><i class="fa fa-check"></i><b>5.2.6</b> Revisiting t-tests</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#revisiting-the-original-questions"><i class="fa fa-check"></i><b>5.3</b> Revisiting the Original Questions</a></li>
<li class="chapter" data-level="5.4" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#r-a-simple-figure-with-two-variables"><i class="fa fa-check"></i><b>5.4</b> R: A Simple Figure With Two Variables</a></li>
<li class="chapter" data-level="5.5" data-path="why-does-hypothesis-testing-work-a-primer-on-probability.html"><a href="why-does-hypothesis-testing-work-a-primer-on-probability.html#reading-for-this-week-1"><i class="fa fa-check"></i><b>5.5</b> Reading for This Week</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="are-different-people-different.html"><a href="are-different-people-different.html"><i class="fa fa-check"></i><b>6</b> Are Different People Different?</a>
<ul>
<li class="chapter" data-level="6.1" data-path="are-different-people-different.html"><a href="are-different-people-different.html#a-recap-from-last-week"><i class="fa fa-check"></i><b>6.1</b> A Recap from Last Week</a></li>
<li class="chapter" data-level="6.2" data-path="are-different-people-different.html"><a href="are-different-people-different.html#what-are-bivariate-relationships"><i class="fa fa-check"></i><b>6.2</b> What Are Bivariate Relationships?</a></li>
<li class="chapter" data-level="6.3" data-path="are-different-people-different.html"><a href="are-different-people-different.html#categorical-data"><i class="fa fa-check"></i><b>6.3</b> Categorical Data</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="are-different-people-different.html"><a href="are-different-people-different.html#describing-the-sample"><i class="fa fa-check"></i><b>6.3.1</b> Describing the Sample</a></li>
<li class="chapter" data-level="6.3.2" data-path="are-different-people-different.html"><a href="are-different-people-different.html#estimating-the-parameters-in-the-population"><i class="fa fa-check"></i><b>6.3.2</b> Estimating the Parameters in the Population</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="are-different-people-different.html"><a href="are-different-people-different.html#continuous-data"><i class="fa fa-check"></i><b>6.4</b> Continuous Data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="are-different-people-different.html"><a href="are-different-people-different.html#describe"><i class="fa fa-check"></i><b>6.4.1</b> Describe</a></li>
<li class="chapter" data-level="6.4.2" data-path="are-different-people-different.html"><a href="are-different-people-different.html#measures-about-the-population"><i class="fa fa-check"></i><b>6.4.2</b> Measures About the Population</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="are-different-people-different.html"><a href="are-different-people-different.html#code"><i class="fa fa-check"></i><b>6.5</b> Code</a></li>
<li class="chapter" data-level="6.6" data-path="are-different-people-different.html"><a href="are-different-people-different.html#reading-for-this-week-2"><i class="fa fa-check"></i><b>6.6</b> Reading for This Week</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html"><i class="fa fa-check"></i><b>7</b> Comparing Apples and Oranges</a>
<ul>
<li class="chapter" data-level="7.1" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#bivariate-regression"><i class="fa fa-check"></i><b>7.1</b> Bivariate Regression</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#how-does-it-work"><i class="fa fa-check"></i><b>7.1.1</b> How Does It Work?</a></li>
<li class="chapter" data-level="7.1.2" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#how-do-we-interpret-results"><i class="fa fa-check"></i><b>7.1.2</b> How Do We Interpret Results?</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#beyond-bivariate-regression"><i class="fa fa-check"></i><b>7.2</b> Beyond Bivariate Regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#bivariate-regression-plus-a-dummy"><i class="fa fa-check"></i><b>7.2.1</b> Bivariate Regression Plus a Dummy</a></li>
<li class="chapter" data-level="7.2.2" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#multivariate-regression"><i class="fa fa-check"></i><b>7.2.2</b> Multivariate Regression</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#the-relevance-of-statistical-control"><i class="fa fa-check"></i><b>7.3</b> The Relevance of Statistical Control</a></li>
<li class="chapter" data-level="7.4" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#r-code"><i class="fa fa-check"></i><b>7.4</b> R Code</a></li>
<li class="chapter" data-level="7.5" data-path="comparing-apples-and-oranges.html"><a href="comparing-apples-and-oranges.html#reading-for-this-week-3"><i class="fa fa-check"></i><b>7.5</b> Reading for This Week</a></li>
</ul></li>
<li class="part"><span><b>Scenario III: Did the New Policy Have an Effect?</b></span></li>
<li class="chapter" data-level="8" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html"><i class="fa fa-check"></i><b>8</b> The Fundamental Problem of Causal Inference</a>
<ul>
<li class="chapter" data-level="8.1" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html#studying-causal-effects"><i class="fa fa-check"></i><b>8.1</b> Studying Causal Effects</a></li>
<li class="chapter" data-level="8.2" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html#key-concepts-1"><i class="fa fa-check"></i><b>8.2</b> Key Concepts</a></li>
<li class="chapter" data-level="8.3" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html#the-fundamental-problem-of-causal-inference-1"><i class="fa fa-check"></i><b>8.3</b> The Fundamental Problem of Causal Inference</a></li>
<li class="chapter" data-level="8.4" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html#randomized-control-trials"><i class="fa fa-check"></i><b>8.4</b> Randomized Control Trials</a></li>
<li class="chapter" data-level="8.5" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html#estimating-a-first-causal-effect"><i class="fa fa-check"></i><b>8.5</b> Estimating a First Causal Effect</a></li>
<li class="chapter" data-level="8.6" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html#plotting-data-on-maps"><i class="fa fa-check"></i><b>8.6</b> Plotting Data on Maps</a></li>
<li class="chapter" data-level="8.7" data-path="the-fundamental-problem-of-causal-inference.html"><a href="the-fundamental-problem-of-causal-inference.html#reading-for-this-week-4"><i class="fa fa-check"></i><b>8.7</b> Reading for This Week</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="causal-statements-from-observational-data.html"><a href="causal-statements-from-observational-data.html"><i class="fa fa-check"></i><b>9</b> Causal Statements from Observational Data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="causal-statements-from-observational-data.html"><a href="causal-statements-from-observational-data.html#this-weeks-data-the-effect-of-the-welsh-circuit-break"><i class="fa fa-check"></i><b>9.1</b> This Week’s Data: The Effect of the Welsh Circuit Break</a></li>
<li class="chapter" data-level="9.2" data-path="causal-statements-from-observational-data.html"><a href="causal-statements-from-observational-data.html#compare-treated-from-one-group-to-the-non-treated-of-another-group"><i class="fa fa-check"></i><b>9.2</b> Compare Treated from One Group to the Non-Treated of Another Group</a></li>
<li class="chapter" data-level="9.3" data-path="causal-statements-from-observational-data.html"><a href="causal-statements-from-observational-data.html#compare-the-treated-before-and-after-their-treatment"><i class="fa fa-check"></i><b>9.3</b> Compare the Treated Before and After their Treatment</a></li>
<li class="chapter" data-level="9.4" data-path="causal-statements-from-observational-data.html"><a href="causal-statements-from-observational-data.html#best-of-both-worlds-the-difference-in-difference-estimator"><i class="fa fa-check"></i><b>9.4</b> Best of Both Worlds: The Difference-in-Difference Estimator</a></li>
<li class="chapter" data-level="9.5" data-path="causal-statements-from-observational-data.html"><a href="causal-statements-from-observational-data.html#reading-for-this-week-5"><i class="fa fa-check"></i><b>9.5</b> Reading for This Week</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multivariate-regression-and-heterogenous-treatment-effects.html"><a href="multivariate-regression-and-heterogenous-treatment-effects.html"><i class="fa fa-check"></i><b>10</b> Multivariate Regression and Heterogenous Treatment Effects</a>
<ul>
<li class="chapter" data-level="10.1" data-path="multivariate-regression-and-heterogenous-treatment-effects.html"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#analysing-experimental-data-revisited"><i class="fa fa-check"></i><b>10.1</b> Analysing Experimental Data Revisited</a></li>
<li class="chapter" data-level="10.2" data-path="multivariate-regression-and-heterogenous-treatment-effects.html"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#controling-for-confounders"><i class="fa fa-check"></i><b>10.2</b> Controling for Confounders</a></li>
<li class="chapter" data-level="10.3" data-path="multivariate-regression-and-heterogenous-treatment-effects.html"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#treatment-heterogeneity"><i class="fa fa-check"></i><b>10.3</b> Treatment Heterogeneity</a></li>
<li class="chapter" data-level="10.4" data-path="multivariate-regression-and-heterogenous-treatment-effects.html"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#outro"><i class="fa fa-check"></i><b>10.4</b> Outro</a></li>
<li class="chapter" data-level="10.5" data-path="multivariate-regression-and-heterogenous-treatment-effects.html"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#reading-for-this-week-6"><i class="fa fa-check"></i><b>10.5</b> Reading for This Week</a></li>
</ul></li>
<li class="part"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="11" data-path="useful-internet-resources.html"><a href="useful-internet-resources.html"><i class="fa fa-check"></i><b>11</b> Useful Internet Resources</a>
<ul>
<li class="chapter" data-level="11.1" data-path="useful-internet-resources.html"><a href="useful-internet-resources.html#homepages"><i class="fa fa-check"></i><b>11.1</b> Homepages</a></li>
<li class="chapter" data-level="11.2" data-path="useful-internet-resources.html"><a href="useful-internet-resources.html#online-books"><i class="fa fa-check"></i><b>11.2</b> Online Books</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PL 9248 Data Science for Politics and IR</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multivariate-regression-and-heterogenous-treatment-effects" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Multivariate Regression and Heterogenous Treatment Effects<a href="multivariate-regression-and-heterogenous-treatment-effects.html#multivariate-regression-and-heterogenous-treatment-effects" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/gAolTBQbSco" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
<div id="analysing-experimental-data-revisited" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Analysing Experimental Data Revisited<a href="multivariate-regression-and-heterogenous-treatment-effects.html#analysing-experimental-data-revisited" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To analyse experimental data, we so far did an easy calculation. We subtracted the average of the control group from the average of the treatment group. It turns out, that you can analyse experimental data with the regression framework from our second section in this class, too.</p>
<p>Let us take a look at this comparison with an example. We want to understand the causal effect of unemployment training. For this purpose, I generated some artificial data for illustration—so no real life data today. In our scenario, people have been unemployed for three months. After three months, we randomly assign a treatment. Half of the unemployed will get a four weeks class that improve on their IT skills. The other half continue in the unemployment programme as is. The outcome we are interested in is the monthly income six months into the new job. This is the result from the (hypothetical) experiment.</p>
<p><img src="intro_data_science_homepage_files/figure-html/unnamed-chunk-151-1.png" width="672" /></p>
<p>As you can see, there is indeed evidence that the training did have an effect. How again did we get to the effect that is caused by the training for the unemployed? We simply calculated the mean of both groups and subtracted them from one another. So we take the average monthly income after 6 months in the new job of those who participated in the training 2850.1 GBP and subtract from it the average monthly income after 6 months in the new job of those who did not participate in the programme 2271.81 GBP. The difference between the two is our causal effect of the programme:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(reg.dat<span class="sc">$</span>wage[reg.dat<span class="sc">$</span>treat <span class="sc">==</span> <span class="dv">1</span>]) <span class="sc">-</span> <span class="fu">mean</span>(reg.dat<span class="sc">$</span>wage[reg.dat<span class="sc">$</span>treat <span class="sc">==</span> <span class="dv">0</span>])</span></code></pre></div>
<pre><code>## [1] 578.2929</code></pre>
<p>But we can get to this result also with a regression analysis:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb157-1" aria-hidden="true" tabindex="-1"></a>regression.result <span class="ot">&lt;-</span> <span class="fu">lm</span>(reg.dat<span class="sc">$</span>wage <span class="sc">~</span> reg.dat<span class="sc">$</span>treat)</span>
<span id="cb157-2"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb157-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression.result)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = reg.dat$wage ~ reg.dat$treat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1701.90  -494.83    22.38   471.43  1960.42 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    2271.81      29.28   77.58   &lt;2e-16 ***
## reg.dat$treat   578.29      41.41   13.96   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 654.8 on 998 degrees of freedom
## Multiple R-squared:  0.1634, Adjusted R-squared:  0.1626 
## F-statistic:   195 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Why do we get to the same results with both ways of calculating it? Remember that for the regression we are calculating the following regression model</p>
<p><span class="math display">\[
Y(X) = \alpha + \beta X + \epsilon.
\]</span>
We interpreted the estimate of the parameter <span class="math inline">\(\hat\beta\)</span> as follows. It is the change of the result in <span class="math inline">\(Y\)</span> if we change the value of <span class="math inline">\(X\)</span> by one unit. In our context this means the change from the control to the treatment group. Let us consider the effects for the two groups, the estimated outcomes in the treatment group <span class="math inline">\(\widehat{Y(X=1)}\)</span> and the estimated outcomes in the control group <span class="math inline">\(\widehat{Y(X=0)}\)</span>:</p>
<p><span class="math display">\[
\widehat{Y(X = 1)} - \widehat{Y(X=0)} = (\hat\alpha - \hat\beta) - \hat\alpha = \hat\beta.
\]</span></p>
<p>So, indeed, the estimated difference between the two outcomes boils down to the estimated parameter <span class="math inline">\(\hat\beta\)</span>.</p>
</div>
<div id="controling-for-confounders" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Controling for Confounders<a href="multivariate-regression-and-heterogenous-treatment-effects.html#controling-for-confounders" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>OK, so the difference between the control group and the treatment group can also be calculated with a regression. Fancy enough. But why going through all this trouble if we can simply subtract the means of two groups? Isn’t that much more easy?</p>
<p>Knowing how to calculate causal effects with the regression framework can be useful in different ways. Let us begin with the problem of confounders. Remember that for our estimator to work, we had to make an important assumption: the treatment assignment really has to be random in both groups. If the assignment is not fully random and the outcome depends on another variable, then we run into problems.</p>
<p>In the context of our running example, we might have collected information on other variables. For example, we recorded participants’ gender and also the number of years they spent in education, which in effect measures how long they spent in school or university.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(reg.dat<span class="sc">$</span>wage <span class="sc">~</span> reg.dat<span class="sc">$</span>treat <span class="sc">+</span> reg.dat<span class="sc">$</span>female))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = reg.dat$wage ~ reg.dat$treat + reg.dat$female)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1757.34  -496.63    23.27   471.01  1906.07 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     2326.16      35.86  64.867  &lt; 2e-16 ***
## reg.dat$treat    579.37      41.30  14.030  &lt; 2e-16 ***
## reg.dat$female  -107.84      41.30  -2.611  0.00916 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 652.9 on 997 degrees of freedom
## Multiple R-squared:  0.1691, Adjusted R-squared:  0.1675 
## F-statistic: 101.5 on 2 and 997 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(reg.dat<span class="sc">$</span>wage <span class="sc">~</span> reg.dat<span class="sc">$</span>treat <span class="sc">+</span> reg.dat<span class="sc">$</span>female <span class="sc">+</span> reg.dat<span class="sc">$</span>education))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = reg.dat$wage ~ reg.dat$treat + reg.dat$female + 
##     reg.dat$education)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1405.03  -267.08    -0.94   259.26  1150.44 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         64.284     57.014   1.128    0.260    
## reg.dat$treat      539.729     24.549  21.985   &lt;2e-16 ***
## reg.dat$female     -38.913     24.589  -1.583    0.114    
## reg.dat$education  154.577      3.614  42.770   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 387.9 on 996 degrees of freedom
## Multiple R-squared:  0.7071, Adjusted R-squared:  0.7062 
## F-statistic: 801.4 on 3 and 996 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We observe the effects from this omission in the two regressions that we can run. First, we are only adding the variable for gender. The variable is not significant, so there is no evidence that we have a systematic effect. The randomization of the treatment worked well.</p>
<p>Things are different when we also add the variable on education. Indeed, the level of education does have an effect on the outcome. For some reason, when designing the experiment there was a mistake in the randomisation of our treatment and in result we do have a bias. If we only use the difference in means estimator, we would have missed this bias. Now that we include education in our regression analysis, we can control for it. In result, the effect from our treatment diminishes is quite strongly.</p>
</div>
<div id="treatment-heterogeneity" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Treatment Heterogeneity<a href="multivariate-regression-and-heterogenous-treatment-effects.html#treatment-heterogeneity" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The other area where the regression framework is really useful is in the context of treatment heterogeneity. Treatment heterogeneity describes the situation where the treatment you are assigning might have different effects on different groups.</p>
<p>For example, in our experiment we could believe that retraining has different effects on different age cohorts. For anybody below 50, IT skills are quite normal and employers would expect that they can all handle a computer well. But what about those who did not grow up with a computer and are 50 years or older? For them, IT skills are much more rare and having this extra training under the belt might give you a real advantage.</p>
<p>How can we express such a relationship with a regression equation? We not only include the terms for the treatment and also the age, but we also multiply the two variables and a parameter we estimate along. For our example, the regression equation would look like the following.</p>
<p><span class="math display">\[
\text{Income} = \beta_0 + \beta_1 \text{Training} + \beta_2 \text{Over 50}
+ \beta_3 \text{Training * Over 50} + \beta_4 \text{Female} + \beta_5 \text{Education}
\]</span></p>
<p>How do we interpret this result for the resulting regression equation? The coefficient <span class="math inline">\(\beta_3\)</span> is activated if both of the data equal <span class="math inline">\(1\)</span>. So only if we observe somebody over <span class="math inline">\(50\)</span> who receives the treatment will we actually notice the impact of the estimated parameter <span class="math inline">\(\beta_3\)</span> on our outcome. If either of the two variables is <span class="math inline">\(0\)</span>, there will be no effect from <span class="math inline">\(\beta_3\)</span> on the income.</p>
<ul>
<li>If the age is below <span class="math inline">\(50\)</span> and this variable equals <span class="math inline">\(0\)</span>, the whole product term equals 0.</li>
<li>Likewise, if there is no treatment, the whole product term is <span class="math inline">\(0\)</span> as well.</li>
</ul>
<p>Overall, we will be able to make the following statement. In addition to the normal treatment effect that we already observe from <span class="math inline">\(\beta_2\)</span>, is there also an additional difference in the treatment for those who are older than 50 years?</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3 Treatment Heterogeneity</span></span>
<span id="cb163-2"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb163-2" aria-hidden="true" tabindex="-1"></a>regression.interaction.result <span class="ot">&lt;-</span> <span class="fu">lm</span>(reg.dat<span class="sc">$</span>wage <span class="sc">~</span> reg.dat<span class="sc">$</span>treat<span class="sc">*</span>reg.dat<span class="sc">$</span>age<span class="fl">.50</span>plus <span class="sc">+</span> reg.dat<span class="sc">$</span>female <span class="sc">+</span> reg.dat<span class="sc">$</span>education)</span>
<span id="cb163-3"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb163-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression.interaction.result)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = reg.dat$wage ~ reg.dat$treat * reg.dat$age.50plus + 
##     reg.dat$female + reg.dat$education)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1401.82  -257.81     1.11   263.65  1080.25 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                        55.588     57.942   0.959    0.338    
## reg.dat$treat                     418.075     34.812  12.009  &lt; 2e-16 ***
## reg.dat$age.50plus                -22.687     34.185  -0.664    0.507    
## reg.dat$female                    -36.905     24.119  -1.530    0.126    
## reg.dat$education                 155.954      3.557  43.841  &lt; 2e-16 ***
## reg.dat$treat:reg.dat$age.50plus  240.940     48.353   4.983 7.38e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 380.4 on 994 degrees of freedom
## Multiple R-squared:  0.7188, Adjusted R-squared:  0.7174 
## F-statistic: 508.2 on 5 and 994 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Taking a look at the regression results, what can we learn? First of all, we see that apparently controlling for this interaction term was really necessary and brought our overall treatment effect baseline treatment effect highly up. It is at 418 GBP and we are quite certain that it is not just random coincidence. Next, just the age does not make any big difference on the income in our example. Neither does actually the difference between men and women. However, education matters—for every extra year that you spent in education you will earn 156 GBP per month more.</p>
<p>Finally, let us also take a look at the interaction turn. We learned that for everyone who is over 50, going through the training gives them an additional advantage of 241 per month. This effect is significant as well, so that we can be quite certain that in the larger population there is an effect that is different from zero.</p>
<p>In sum, those who are below <span class="math inline">\(50\)</span> and go through the IT training can expect an income increase of 418 GBP per month. In addition, those who are older than <span class="math inline">\(50\)</span> can add an extra 241 GBP to this baseline treatment effect summing to overall 659.</p>
<p>Let me explain you this interaction effect in a quick video again.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/qKW9LxE-sP0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
<p>By the way, here is the ‘real’ data generating process that I defined to get to our data. You can clearly see that all our estimates of the treatment effect are off if the model is not appropriate—be it with a simple calculation of the difference in means or ‘wrongly’ specified regression models. We only get regression results close to the ‘real’ coefficients in the data generating process if we correctly specify the regression equation.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Explanatory Variables</span></span>
<span id="cb165-2"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb165-2" aria-hidden="true" tabindex="-1"></a>education <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq</span>(<span class="dv">9</span>, <span class="dv">20</span>), <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb165-3"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb165-3" aria-hidden="true" tabindex="-1"></a>treat <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">500</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">500</span>))</span>
<span id="cb165-4"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb165-4" aria-hidden="true" tabindex="-1"></a>age<span class="fl">.50</span>plus <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="dv">1000</span>)</span>
<span id="cb165-5"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb165-5" aria-hidden="true" tabindex="-1"></a>female <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dv">1000</span>, <span class="at">replace  =</span> <span class="cn">TRUE</span>)</span>
<span id="cb165-6"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb165-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Outcome</span></span>
<span id="cb165-7"><a href="multivariate-regression-and-heterogenous-treatment-effects.html#cb165-7" aria-hidden="true" tabindex="-1"></a>wage <span class="ot">&lt;-</span> education <span class="sc">*</span> <span class="dv">160</span> <span class="sc">+</span> treat <span class="sc">*</span> <span class="dv">400</span> <span class="sc">+</span> age<span class="fl">.50</span>plus<span class="sc">*</span>treat<span class="sc">*</span><span class="dv">250</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="dv">0</span>, <span class="dv">400</span>)</span></code></pre></div>
</div>
<div id="outro" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Outro<a href="multivariate-regression-and-heterogenous-treatment-effects.html#outro" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This Is It! What an amazing journey we had! Please allow me a couple of final words.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/eO3S2ikqaMA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>
<div id="reading-for-this-week-6" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Reading for This Week<a href="multivariate-regression-and-heterogenous-treatment-effects.html#reading-for-this-week-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this last week, please read p.161–181 in <span class="citation">Imai (<a href="#ref-Imai2018" role="doc-biblioref">2018</a>)</span>.</p>

</div>
</div>



<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Imai2018" class="csl-entry">
Imai, Kosuke. 2018. <em>Quantitative Social Science–an Introduction</em>. Princeton University Press.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="causal-statements-from-observational-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="useful-internet-resources.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["intro_data_science_homepage.pdf", "intro_data_science_homepage.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
